[project]
name = "wampi"
version = "0.1.0"
description = "Watchmode title sources API wrapper."
readme = "README.md"
requires-python = ">=3.14"
authors = [
  { name = "ryn-cx", email = "262888154+ryn-cx@users.noreply.github.com" }
]
dependencies = [
  "get-around",
  "pydantic>=2",
]

[dependency-groups]
dev = [
  "prek>=0.3.2",
  "pytest>=8.4.2",
  "ruff>=0.13.3",
  "ty>=0.0.72",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "CPY001",  # Copyright information is stored in LICENSE.
  "D",  # Docstrings are not required.
  "FIX002",  # TODO comments are allowed.
  "TD002",  # TODO comments do not need an author.
  "TD003",  # TODO comments do not need an issue link.
]

extend-select = [
  "D400",  # Checks for docstrings in which the first line does not end in a period.
  "D401",  # Checks for docstring first lines that are not in an imperative mood.
  "D404",  # Checks for function docstrings that include the function's signature in the summary line.
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]  # Asserts are allowed in tests.

[tool.uv.sources]
get-around = { git = "https://github.com/ryn-cx/get-around" }

[tool.ty.rules]
all = "error"
